"""Add Empresa, UnidadeAegea, Material, LogAuditoria

Revision ID: 005a5c5682f3
Revises: 4faff1819a9b
Create Date: 2026-03-25 12:44:07.576092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005a5c5682f3'
down_revision: Union[str, Sequence[str], None] = '4faff1819a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EMPRESAS',
    sa.Column('EmpresaID', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('Nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('EmpresaID')
    )
    op.create_table('LOGS_AUDITORIA',
    sa.Column('LogID', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('Acao', sa.String(length=100), nullable=False),
    sa.Column('TabelaAfetada', sa.String(length=100), nullable=True),
    sa.Column('RegistroID', sa.String(length=100), nullable=True),
    sa.Column('UsuarioID', sa.String(length=100), nullable=True),
    sa.Column('DetalhesAntigos', sa.Unicode(), nullable=True),
    sa.Column('DetalhesNovos', sa.Unicode(), nullable=True),
    sa.Column('DataHora', sa.DateTime(), server_default=sa.text('(getdate())'), nullable=False),
    sa.PrimaryKeyConstraint('LogID')
    )
    op.create_table('MATERIAIS',
    sa.Column('MaterialID', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('Descricao', sa.String(length=200), nullable=False),
    sa.Column('TipoMaterial', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('MaterialID')
    )

    op.create_table('UNIDADES_AEGEA',
    sa.Column('UnidadeAegeaID', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('EmpresaID', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(length=200), nullable=False),
    sa.Column('Regiao', sa.String(length=100), nullable=True),
    sa.Column('Estado', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['EmpresaID'], ['EMPRESAS.EmpresaID'], ),
    sa.PrimaryKeyConstraint('UnidadeAegeaID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UNIDADES_AEGEA')

    op.drop_table('MATERIAIS')
    op.drop_table('LOGS_AUDITORIA')
    op.drop_table('EMPRESAS')
    # ### end Alembic commands ###
