"""Add optional columns to Unidade, Serviço, Parceiro, Pedido

Revision ID: 018ac14de9dc
Revises: 005a5c5682f3
Create Date: 2026-03-25 12:53:16.720688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018ac14de9dc'
down_revision: Union[str, Sequence[str], None] = '005a5c5682f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('CATALOGO_TIPOS_SERVICO', sa.Column('TipoVeiculo', sa.String(length=50), nullable=True))
    op.add_column('CATALOGO_TIPOS_SERVICO', sa.Column('EPI', sa.String(length=50), nullable=True))
    op.add_column('CATALOGO_TIPOS_SERVICO', sa.Column('Perfil', sa.String(length=50), nullable=True))
    op.add_column('CATALOGO_TIPOS_SERVICO', sa.Column('FormularioResposta', sa.String(length=100), nullable=True))
    op.add_column('PARCEIROS_PERFIL', sa.Column('UnidadeID', sa.Integer(), nullable=True))
    op.add_column('PARCEIROS_PERFIL', sa.Column('Qualificacao_DDI', sa.String(length=50), nullable=True))
    op.add_column('PARCEIROS_PERFIL', sa.Column('TreinamentoFlag', sa.Boolean(), server_default=sa.text('((0))'), nullable=True))
    op.add_column('PARCEIROS_PERFIL', sa.Column('Perfil', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'PARCEIROS_PERFIL', 'UNIDADES', ['UnidadeID'], ['UnidadeID'])
    op.add_column('PEDIDOS_SERVICO', sa.Column('MatriculaSCAE', sa.String(length=50), nullable=True))
    op.add_column('PEDIDOS_SERVICO', sa.Column('NumeroOSSCAE', sa.String(length=100), nullable=True))
    op.alter_column('PEDIDOS_SERVICO', 'Urgencia',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('UNIDADES', sa.Column('UnidadeAegeaID', sa.Integer(), nullable=True))
    op.add_column('UNIDADES', sa.Column('CodigoUnidadeAegea', sa.String(length=50), nullable=True))
    op.add_column('UNIDADES', sa.Column('Bloco', sa.String(length=50), nullable=True))
    op.add_column('UNIDADES', sa.Column('FornecimentoMateriais', sa.Unicode(), nullable=True))
    op.create_foreign_key(None, 'UNIDADES', 'UNIDADES_AEGEA', ['UnidadeAegeaID'], ['UnidadeAegeaID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UNIDADES', type_='foreignkey')
    op.drop_column('UNIDADES', 'FornecimentoMateriais')
    op.drop_column('UNIDADES', 'Bloco')
    op.drop_column('UNIDADES', 'CodigoUnidadeAegea')
    op.drop_column('UNIDADES', 'UnidadeAegeaID')
    op.alter_column('PEDIDOS_SERVICO', 'Urgencia',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_column('PEDIDOS_SERVICO', 'NumeroOSSCAE')
    op.drop_column('PEDIDOS_SERVICO', 'MatriculaSCAE')
    op.drop_constraint(None, 'PARCEIROS_PERFIL', type_='foreignkey')
    op.drop_column('PARCEIROS_PERFIL', 'Perfil')
    op.drop_column('PARCEIROS_PERFIL', 'TreinamentoFlag')
    op.drop_column('PARCEIROS_PERFIL', 'Qualificacao_DDI')
    op.drop_column('PARCEIROS_PERFIL', 'UnidadeID')
    op.drop_column('CATALOGO_TIPOS_SERVICO', 'FormularioResposta')
    op.drop_column('CATALOGO_TIPOS_SERVICO', 'Perfil')
    op.drop_column('CATALOGO_TIPOS_SERVICO', 'EPI')
    op.drop_column('CATALOGO_TIPOS_SERVICO', 'TipoVeiculo')

    # ### end Alembic commands ###
