"""Ajustes no bd

Revision ID: 0bd830353e81
Revises: 40838bb2f857
Create Date: 2026-04-07 16:29:44.370851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd830353e81'
down_revision: Union[str, Sequence[str], None] = '40838bb2f857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Migration para adicionar novo status em constraint -> Referente à nova funcionalidade de agrupamento de serviços
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE PEDIDOS_SERVICO DROP CONSTRAINT CK_Pedido_Status")
    
    # AGRUPADO incluso
    op.execute("""
        ALTER TABLE PEDIDOS_SERVICO ADD CONSTRAINT CK_Pedido_Status 
        CHECK (StatusPedido IN ('FINALIZADO', 'CANCELADO', 'VINCULADO', 'AGUARDANDO', 'AGRUPADO'))
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE PEDIDOS_SERVICO DROP CONSTRAINT CK_Pedido_Status")
    op.execute("""
        ALTER TABLE PEDIDOS_SERVICO ADD CONSTRAINT CK_Pedido_Status 
        CHECK (StatusPedido IN ('FINALIZADO', 'CANCELADO', 'VINCULADO', 'AGUARDANDO'))
    """)
    # ### end Alembic commands ###
