"""Ajustes no bd

Revision ID: 13bfe2b1777d
Revises: 7caa964a2b6e
Create Date: 2026-04-06 17:48:00.298903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13bfe2b1777d'
down_revision: Union[str, Sequence[str], None] = '7caa964a2b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AGRUPAMENTO_OS', sa.Column('EvidenciaEnviada', sa.Boolean(), server_default=sa.text('(0)'), nullable=False))
    op.add_column('CATALOGO_SERVICOS', sa.Column('TempoMedioExecucao', sa.Float(), nullable=True))
    op.add_column('CATALOGO_SERVICOS', sa.Column('TempoMaximo', sa.Float(), nullable=True))
    op.drop_column('PRECOS_SERVICOS_UNIDADE', 'TempoMaximo')
    op.drop_column('PRECOS_SERVICOS_UNIDADE', 'TempoMedioExecucao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PRECOS_SERVICOS_UNIDADE', sa.Column('TempoMedioExecucao', sa.FLOAT(precision=53), autoincrement=False, nullable=True))
    op.add_column('PRECOS_SERVICOS_UNIDADE', sa.Column('TempoMaximo', sa.FLOAT(precision=53), autoincrement=False, nullable=True))
    op.drop_column('CATALOGO_SERVICOS', 'TempoMaximo')
    op.drop_column('CATALOGO_SERVICOS', 'TempoMedioExecucao')
    op.drop_column('AGRUPAMENTO_OS', 'EvidenciaEnviada')
    # ### end Alembic commands ###
