"""altera tipo da coluna e cria relacao com tipo de veiculo

Revision ID: 21af4d573e95
Revises: a3ba5be8c920
Create Date: 2026-04-01 15:06:58.960642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '21af4d573e95'
down_revision: Union[str, Sequence[str], None] = 'a3ba5be8c920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CATALOGO_SERVICOS', 'TipoVeiculo',
               existing_type=sa.VARCHAR(length=4, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Integer(),
               nullable=True)
    op.create_foreign_key('FK__CATALOGO___Tipo__VEICULOID', 'CATALOGO_SERVICOS', 'TIPOS_VEICULOS', ['TipoVeiculo'], ['TipoVeiculoID'])
    op.alter_column('PEDIDOS_SERVICO', 'PrazoConclusaoOS',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('SERVICOS_UNIDADES_MATERIAIS', 'Obrigatorio',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SERVICOS_UNIDADES_MATERIAIS', 'Obrigatorio',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
    op.alter_column('PEDIDOS_SERVICO', 'PrazoConclusaoOS',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_constraint(None, 'CATALOGO_SERVICOS', type_='foreignkey')
    op.alter_column('CATALOGO_SERVICOS', 'TipoVeiculo',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=4, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###
