"""Make fields mandatory

Revision ID: 27fabd46cfa2
Revises: e1441aed576e
Create Date: 2026-04-24 15:19:02.482613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fabd46cfa2'
down_revision: Union[str, Sequence[str], None] = 'e1441aed576e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    
    
    
    
    op.alter_column('PEDIDOS_SERVICO', 'MatriculaSCAE',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('PEDIDOS_SERVICO', 'NumeroOSSCAE',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('PEDIDOS_SERVICO', 'Numero',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('PEDIDOS_SERVICO', 'Bloco',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('PEDIDOS_SERVICO', 'Urgencia',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('PEDIDOS_SERVICO', 'PrazoConclusaoOS',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('PEDIDOS_SERVICO', 'DataAberturaSCAE',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('PEDIDOS_SERVICO', 'StatusPedido',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("('AGUARDANDO_PARCEIRO')"))
    op.alter_column('PEDIDOS_SERVICO', 'Valor',
               existing_type=sa.FLOAT(precision=53),
               nullable=False)
    op.alter_column('PEDIDOS_SERVICO', 'UnidadeID',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PEDIDOS_SERVICO', 'UnidadeID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('PEDIDOS_SERVICO', 'Valor',
               existing_type=sa.FLOAT(precision=53),
               nullable=True)
    op.alter_column('PEDIDOS_SERVICO', 'StatusPedido',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("('AGUARDANDO_PARCEIRO')"))
    op.alter_column('PEDIDOS_SERVICO', 'DataAberturaSCAE',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('PEDIDOS_SERVICO', 'PrazoConclusaoOS',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('PEDIDOS_SERVICO', 'Urgencia',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('PEDIDOS_SERVICO', 'Bloco',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('PEDIDOS_SERVICO', 'Numero',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('PEDIDOS_SERVICO', 'NumeroOSSCAE',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('PEDIDOS_SERVICO', 'MatriculaSCAE',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
                            # ### end Alembic commands ###
