"""Add PrecoServicoUnidade and ServicoUnidadeMaterial

Revision ID: 2a31e1dcf6c5
Revises: 018ac14de9dc
Create Date: 2026-03-25 14:00:12.572425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a31e1dcf6c5'
down_revision: Union[str, Sequence[str], None] = '018ac14de9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('PRECOS_SERVICOS_UNIDADE',
    sa.Column('UnidadeID', sa.Integer(), nullable=False),
    sa.Column('ServicoItemID', sa.Integer(), nullable=False),
    sa.Column('Preco', sa.Float(precision=53), nullable=False),
    sa.Column('TempoMedioExecucao', sa.Float(), nullable=True),
    sa.Column('TempoMaximo', sa.Float(), nullable=True),
    sa.Column('FatorExtra', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ServicoItemID'], ['CATALOGO_TIPOS_SERVICO.ServicoItemID'], ),
    sa.ForeignKeyConstraint(['UnidadeID'], ['UNIDADES.UnidadeID'], ),
    sa.PrimaryKeyConstraint('UnidadeID', 'ServicoItemID')
    )
    op.create_table('SERVICOS_UNIDADES_MATERIAIS',
    sa.Column('UnidadeID', sa.Integer(), nullable=False),
    sa.Column('ServicoItemID', sa.Integer(), nullable=False),
    sa.Column('MaterialID', sa.Integer(), nullable=False),
    sa.Column('Obrigatorio', sa.Boolean(), server_default=sa.text('((0))'), nullable=True),
    sa.ForeignKeyConstraint(['MaterialID'], ['MATERIAIS.MaterialID'], ),
    sa.ForeignKeyConstraint(['ServicoItemID'], ['CATALOGO_TIPOS_SERVICO.ServicoItemID'], ),
    sa.ForeignKeyConstraint(['UnidadeID'], ['UNIDADES.UnidadeID'], ),
    sa.PrimaryKeyConstraint('UnidadeID', 'ServicoItemID', 'MaterialID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SERVICOS_UNIDADES_MATERIAIS')
    op.drop_table('PRECOS_SERVICOS_UNIDADE')

    # ### end Alembic commands ###
