"""Adiciona lat e lng em pedidos

Revision ID: 40838bb2f857
Revises: 13bfe2b1777d
Create Date: 2026-04-06 17:55:49.349330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40838bb2f857'
down_revision: Union[str, Sequence[str], None] = '13bfe2b1777d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PEDIDOS_SERVICO', sa.Column('Lat', sa.Float(precision=53), nullable=True))
    op.add_column('PEDIDOS_SERVICO', sa.Column('Lng', sa.Float(precision=53), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PEDIDOS_SERVICO', 'Lng')
    op.drop_column('PEDIDOS_SERVICO', 'Lat')
    # ### end Alembic commands ###
