"""Adicionando tabelas de Agrupamento de OS

Revision ID: 7caa964a2b6e
Revises: f1ca5d4837c1
Create Date: 2026-04-02 18:20:12.407741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7caa964a2b6e'
down_revision: Union[str, Sequence[str], None] = 'f1ca5d4837c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OS_AGRUPADAS',
    sa.Column('AgrupamentoID', sa.Uuid(), server_default=sa.text('(newid())'), nullable=False),
    sa.Column('NomeAgrupamento', sa.String(length=255), nullable=False),
    sa.Column('Descricao', sa.String(length=255), nullable=True),
    sa.Column('DataCriacao', sa.DateTime(), server_default=sa.text('(getdate())'), nullable=False),
    sa.Column('CriadoPor', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('AgrupamentoID')
    )
    op.create_table('AGRUPAMENTO_OS',
    sa.Column('AgrupamentoOSPedidoID', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('AgrupamentoID', sa.Uuid(), nullable=False),
    sa.Column('PedidoID', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['AgrupamentoID'], ['OS_AGRUPADAS.AgrupamentoID'], ),
    sa.ForeignKeyConstraint(['PedidoID'], ['PEDIDOS_SERVICO.PedidoID'], ),
    sa.PrimaryKeyConstraint('AgrupamentoOSPedidoID')
    )
    op.add_column('PEDIDOS_SERVICO', sa.Column('CriadoPor', sa.String(length=255), nullable=False, server_default=sa.text("('SYSTEM')")))
    op.alter_column('TIPOS_VEICULOS', 'Descricao', new_column_name='NomeVeiculo', existing_type=sa.String(length=50), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TIPOS_VEICULOS', sa.Column('Descricao', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_column('TIPOS_VEICULOS', 'NomeVeiculo')
    op.drop_column('PEDIDOS_SERVICO', 'CriadoPor')
    op.drop_table('AGRUPAMENTO_OS')
    op.drop_table('OS_AGRUPADAS')
    # ### end Alembic commands ###
