"""Add Servico Table

Revision ID: 917c74710f72
Revises: b76d4095fc37
Create Date: 2026-03-25 16:44:02.001773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917c74710f72'
down_revision: Union[str, Sequence[str], None] = 'b76d4095fc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SERVICOS',
    sa.Column('ServicoID', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('UnidadeID', sa.Integer(), nullable=False),
    sa.Column('CodigoServico', sa.String(length=50), nullable=False),
    sa.Column('Descricao', sa.String(length=200), nullable=False),
    sa.Column('TipoVeiculo', sa.String(length=50), nullable=True),
    sa.Column('EPI', sa.String(length=10), nullable=True),
    sa.Column('Perfil', sa.String(length=50), nullable=True),
    sa.Column('FormularioResposta', sa.String(length=500), nullable=True),
    sa.Column('Preco', sa.Float(precision=53), nullable=True),
    sa.Column('TempoMedioExecucao', sa.Float(), nullable=True),
    sa.Column('TempoMaximo', sa.Float(), nullable=True),
    sa.Column('FatorExtra', sa.Float(), nullable=True),
    sa.Column('Ativo', sa.Boolean(), server_default=sa.text('((1))'), nullable=True),
    sa.ForeignKeyConstraint(['UnidadeID'], ['UNIDADES.UnidadeID'], ),
    sa.PrimaryKeyConstraint('ServicoID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SERVICOS')
    # ### end Alembic commands ###
