"""ajuste para usar pedido no lugar de ordem

Revision ID: b3119296a232
Revises: 21af4d573e95
Create Date: 2026-04-01 16:30:50.785971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'b3119296a232'
down_revision: Union[str, Sequence[str], None] = '21af4d573e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EXECUCAO_PASSOS_RASTREAVEIS', sa.Column('PedidoID', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('FK__EXECUCAO___Ordem__793DFFAF'), 'EXECUCAO_PASSOS_RASTREAVEIS', type_='foreignkey')
    op.create_foreign_key(None, 'EXECUCAO_PASSOS_RASTREAVEIS', 'PEDIDOS_SERVICO', ['PedidoID'], ['PedidoID'])
    op.drop_column('EXECUCAO_PASSOS_RASTREAVEIS', 'OrdemID')
    op.add_column('INTERACOES_CHAT', sa.Column('PedidoID', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('FK__INTERACOE__Ordem__7EF6D905'), 'INTERACOES_CHAT', type_='foreignkey')
    op.create_foreign_key(None, 'INTERACOES_CHAT', 'PEDIDOS_SERVICO', ['PedidoID'], ['PedidoID'])
    op.drop_column('INTERACOES_CHAT', 'OrdemID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('INTERACOES_CHAT', sa.Column('OrdemID', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'INTERACOES_CHAT', type_='foreignkey')
    op.create_foreign_key(op.f('FK__INTERACOE__Ordem__7EF6D905'), 'INTERACOES_CHAT', 'ORDENS_SERVICO', ['OrdemID'], ['OrdemID'])
    op.drop_column('INTERACOES_CHAT', 'PedidoID')
    op.add_column('EXECUCAO_PASSOS_RASTREAVEIS', sa.Column('OrdemID', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'EXECUCAO_PASSOS_RASTREAVEIS', type_='foreignkey')
    op.create_foreign_key(op.f('FK__EXECUCAO___Ordem__793DFFAF'), 'EXECUCAO_PASSOS_RASTREAVEIS', 'ORDENS_SERVICO', ['OrdemID'], ['OrdemID'])
    op.drop_column('EXECUCAO_PASSOS_RASTREAVEIS', 'PedidoID')
    # ### end Alembic commands ###
