"""Ajustes no bd

Revision ID: c8f9bdd24318
Revises: 0bd830353e81
Create Date: 2026-04-07 16:35:35.840264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f9bdd24318'
down_revision: Union[str, Sequence[str], None] = '0bd830353e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('AGRUPAMENTO_OS', sa.Column('DataVinculo', sa.DateTime(), server_default=sa.text('(getdate())'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AGRUPAMENTO_OS', 'DataVinculo')
    # ### end Alembic commands ###
