"""Remove Valor and make Parceiro FKs mandatory

Revision ID: cce0ce79c374
Revises: 2a31e1dcf6c5
Create Date: 2026-03-25 14:18:40.971352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce0ce79c374'
down_revision: Union[str, Sequence[str], None] = '2a31e1dcf6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('CATALOGO_TIPOS_SERVICO', 'Valor')

    op.execute('''
        IF NOT EXISTS (SELECT 1 FROM CATALOGO_REGIOES WHERE NomeRegiao = 'Migration Default')
        BEGIN
            INSERT INTO CATALOGO_REGIOES (NomeRegiao) VALUES ('Migration Default')
            DECLARE @RegID INT = SCOPE_IDENTITY()
            INSERT INTO CATALOGO_SUBREGIOES (RegiaoID, NomeSubregiao) VALUES (@RegID, 'Default')
            DECLARE @SubID INT = SCOPE_IDENTITY()
            INSERT INTO CATALOGO_CIDADES_PARA (SubregiaoID, NomeCidade) VALUES (@SubID, 'Default')
            DECLARE @CidID INT = SCOPE_IDENTITY()
            INSERT INTO EMPRESAS (Nome) VALUES ('Default Company')
            DECLARE @EmpID INT = SCOPE_IDENTITY()
            INSERT INTO UNIDADES_AEGEA (EmpresaID, Nome) VALUES (@EmpID, 'Default Unit')
            DECLARE @UniAegID INT = SCOPE_IDENTITY()
            
            INSERT INTO UNIDADES (CidadeID, NomeUnidade, UnidadeAegeaID) VALUES (@CidID, 'Migration Unit', @UniAegID)
        END
        
        DECLARE @DefaultUniID INT
        SELECT TOP 1 @DefaultUniID = UnidadeID FROM UNIDADES WHERE NomeUnidade = 'Migration Unit'
        
        UPDATE PARCEIROS_PERFIL SET UnidadeID = @DefaultUniID WHERE UnidadeID IS NULL
        UPDATE PARCEIROS_PERFIL SET Qualificacao_DDI = 'PADRAO' WHERE Qualificacao_DDI IS NULL
        UPDATE PARCEIROS_PERFIL SET Perfil = 'GERAL' WHERE Perfil IS NULL
    ''')

    op.alter_column('PARCEIROS_PERFIL', 'UnidadeID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('PARCEIROS_PERFIL', 'Qualificacao_DDI',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('PARCEIROS_PERFIL', 'Perfil',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PARCEIROS_PERFIL', 'Perfil',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('PARCEIROS_PERFIL', 'Qualificacao_DDI',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('PARCEIROS_PERFIL', 'UnidadeID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('CATALOGO_TIPOS_SERVICO', sa.Column('Valor', sa.FLOAT(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
