"""Rename UnidadeAegea to Filial

Revision ID: e7a8d30d4c74
Revises: cce0ce79c374
Create Date: 2026-03-25 15:13:43.535906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a8d30d4c74'
down_revision: Union[str, Sequence[str], None] = 'cce0ce79c374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('FILIAIS',
    sa.Column('FilialID', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('EmpresaID', sa.Integer(), nullable=False),
    sa.Column('Nome', sa.String(length=200), nullable=False),
    sa.Column('Regiao', sa.String(length=100), nullable=True),
    sa.Column('Estado', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['EmpresaID'], ['EMPRESAS.EmpresaID'], ),
    sa.PrimaryKeyConstraint('FilialID')
    )
    
    op.execute("""
        IF EXISTS (SELECT 1 FROM UNIDADES_AEGEA)
        BEGIN
            SET IDENTITY_INSERT FILIAIS ON;
            INSERT INTO FILIAIS (FilialID, EmpresaID, Nome, Regiao, Estado)
            SELECT UnidadeAegeaID, EmpresaID, Nome, Regiao, Estado FROM UNIDADES_AEGEA;
            SET IDENTITY_INSERT FILIAIS OFF;
        END
    """)
    
    op.add_column('UNIDADES', sa.Column('FilialID', sa.Integer(), nullable=True))
    op.add_column('UNIDADES', sa.Column('CodigoFilial', sa.String(length=50), nullable=True))
    
    op.execute("""
        UPDATE UNIDADES SET FilialID = UnidadeAegeaID, CodigoFilial = CodigoUnidadeAegea
    """)
    
    # We must determine dynamic constraint name for UNIDADES.UnidadeAegeaID
    connection = op.get_bind()
    constraint_name = connection.execute(sa.text("SELECT name FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('UNIDADES') AND referenced_object_id = OBJECT_ID('UNIDADES_AEGEA')")).scalar()
    if constraint_name:
        op.execute(f"ALTER TABLE UNIDADES DROP CONSTRAINT {constraint_name}")
    
    op.drop_table('UNIDADES_AEGEA')
    op.create_foreign_key(None, 'UNIDADES', 'FILIAIS', ['FilialID'], ['FilialID'])
    op.drop_column('UNIDADES', 'UnidadeAegeaID')
    op.drop_column('UNIDADES', 'CodigoUnidadeAegea')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UNIDADES', sa.Column('CodigoUnidadeAegea', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('UNIDADES', sa.Column('UnidadeAegeaID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'UNIDADES', type_='foreignkey')
    op.create_foreign_key(op.f('FK__UNIDADES__Unidad__4C6B5938'), 'UNIDADES', 'UNIDADES_AEGEA', ['UnidadeAegeaID'], ['UnidadeAegeaID'])
    op.drop_column('UNIDADES', 'CodigoFilial')
    op.drop_column('UNIDADES', 'FilialID')
    op.create_table('UNIDADES_AEGEA',
    sa.Column('UnidadeAegeaID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('EmpresaID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Nome', sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Regiao', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Estado', sa.VARCHAR(length=2, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['EmpresaID'], ['EMPRESAS.EmpresaID'], name=op.f('FK__UNIDADES___Empre__498EEC8D')),
    sa.PrimaryKeyConstraint('UnidadeAegeaID', name=op.f('PK__UNIDADES__0220528FD6D857E7'))
    )
    op.drop_table('FILIAIS')

